CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE EMP(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    F_NAME VARCHAR(100) NOT NULL,
    L_NAME VARCHAR(100) NOT NULL,
    DEPT VARCHAR(100) NOT NULL,
    SALARY BIGINT DEFAULT 25000
);

ALTER TABLE EMP AUTO_INCREMENT = 100;

-- INSERT 10 EMPLOYEE RECORDS INTO EMP TABLE.
INSERT INTO EMP(F_NAME,L_NAME,DEPT,SALARY)
VALUES
('Amit', 'Sharma', 'HR', 50000),
('Neha', 'Verma', 'IT', 65000),
('Raj', 'Patel', 'Engineering', 72000),
('Priya', 'Nair', 'Marketing', 55000),
('Vikram', 'Singh', 'Sales', 48000),
('Kavita', 'Gupta', 'HR', NULL),  -- Default salary will be used
('Rohit', 'Mehta', 'IT', 68000),
('Anjali', 'Kapoor', 'Engineering', NULL),  -- Default salary will be used
('Suresh', 'Menon', 'Marketing', 56000),
('Govardhan', 'Singh', 'Admin', NULL),
('Krishna','Deshmukh','Development',100000),
('Sneha', 'Reddy', 'Sales', NULL);

set sql_safe_updates = 0;
UPDATE EMP
SET SALARY = 45000
WHERE F_NAME = 'Kavita';
UPDATE EMP
SET SALARY = 45500
WHERE F_NAME = 'Anjali';
UPDATE EMP
SET SALARY = 46000
WHERE F_NAME = 'Govardhan';
UPDATE EMP
SET SALARY = 47000
WHERE F_NAME = 'Sneha';

-- RETRIEVE DETAILS OF EMPLOYEES WHO WORK IN SALES DEPARTMENT
SELECT * FROM EMP 
WHERE DEPT = 'Sales';

-- UPDATE SALARY OF EMPLOYEE TO 55000 HAVING EMP_ID AS 101
UPDATE EMP
SET SALARY = 55000
WHERE EMP_ID = 101;
SELECT * FROM EMP;

-- DELETE EMPLOYEE HAVING ID 105
DELETE FROM EMP
WHERE EMP_ID = 105;
SELECT * FROM EMP;

-- FIND AVERAGE SALARY OF EMPLOYEE IN EACH DEPARTMENT
SELECT DEPT, AVG(SALARY) FROM EMP
GROUP BY(DEPT);

-- LIST NAMES OF EMP WHO EARN MORE THAN AVERAGE SALARY
SELECT F_NAME,L_NAME,SALARY,DEPT FROM EMP 
WHERE SALARY > (SELECT AVG(SALARY) FROM EMP);

-- RETRIEVE THE NAMES OF EMPLOYEES WHO WORK IN EITHER ENGINEERING OR HR DEPARTMENT
SELECT * FROM EMP
WHERE DEPT = 'Engineering' OR DEPT = 'HR';

-- RETRIEVE THE FULL NAME OF ALL EMPLOYEES (CONCATANATE F_NAME AND L_NAME) AND THEIR NAME
SELECT EMP_ID, CONCAT(F_NAME, ' ', L_NAME) AS 'EMPLOYEE NAME', DEPT, SALARY FROM EMP;

-- RETRIEVE DETAILS OF EMPLOYEES WHO WORK IN FINANCE AND IT DEPARTMENT USING IN OPERATOR
SELECT * FROM EMP
WHERE DEPT IN ('Finance','IT');

-- RETRIEVE THE DETAILS OF ALL EMPLOYEE WHOSE LAST NAME START WITH 'S'
SELECT * FROM EMP
WHERE L_NAME LIKE "S%";


-- COUNT THE NO.OF EMPLOYEES IN EACH DEPARTMENT
SELECT DEPT,COUNT(F_NAME) FROM EMP
GROUP BY DEPT
ORDER BY DEPT ASC;

-- RETRIEVE THE NAMES OF EMPLOYEE IN BOTH ENGINEERING AND DEVELOPMENT
SELECT * FROM EMP
WHERE DEPT = 'Engineering' AND DEPT = 'Development';

-- RETRIEVE DETAILS OF THE EMPLOYEE WHO DO NOT WORK IN ADMIN DEPARTMENT
SELECT * FROM EMP 
WHERE DEPT NOT IN ('Admin');

-- FIND HIGHEST SALARY IN EACH DEPT
SELECT DEPT, MAX(SALARY) FROM EMP
GROUP BY DEPT;

-- FIND EMPLOYEES HAVING SALARY BETWEEN 45000 AND 47000
SELECT * FROM EMP
WHERE SALARY BETWEEN 45000 AND 47000;



