CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE student(
	rollno INT PRIMARY KEY,
    STU_NAME VARCHAR(100),
    MARKS FLOAT,
    GRADE VARCHAR(10),
    CITY VARCHAR(100)
);

ALTER TABLE student MODIFY MARKS FLOAT NOT NULL;
ALTER TABLE student MODIFY GRADE VARCHAR(10) NOT NULL;
ALTER TABLE student MODIFY CITY VARCHAR(100) NOT NULL;

INSERT INTO student(rollno, STU_NAME, MARKS, GRADE, CITY)
VALUES
(1,"Ramesh",96,"A","Pune"),
(2,"Lamesh",92,"A","Rune"),
(3,"Samesh",91,"A","June"),
(4,"Jamesh",98,"A","Dune");

SELECT * FROM student;
SELECT STU_NAME, MARKS FROM student;

-- WHERE CLAUSE USE
SELECT * FROM student WHERE MARKS = 96;
SELECT * FROM student WHERE MARKS - 10 >= 85;
SELECT * FROM student WHERE MARKS > 95 AND CITY = "Pune";
select * FROM student WHERE MARKS BETWEEN 91 AND 93; 
SELECT * FROM student WHERE CITY IN ("Pune");
SELECT * FROM student WHERE CITY NOT IN ("Pune");
SELECT * FROM student LIMIT 3;
SELECT * FROM student ORDER BY MARKS ASC; -- ASCENDING ORDER 
SELECT * FROM student ORDER BY MARKS DESC; -- DESCENDING ORDER
SELECT * FROM student ORDER BY STU_NAME DESC;
SELECT COUNT(STU_NAME) FROM student;
SELECT MAX(MARKS) FROM student;
SELECT SUM(MARKS) FROM student;